### ISSUE TITLE
Allow templates to extend other templates

### ISSUE THREAD

**Issue by jonahwh** [pullapprove/support#103]
We like to have all of our templates exist in the pullapprove web UI, so they can be modified outside of our normal approval/CI/CD cycle.

Unfortunately, we can't extend templates from templates, so we can't have one "default" template, and then a bunch of other templates extending from that one. This means we can't have minimal pullapprove configs in our repos, 
```yaml
version: 2
extends: repo-name
```

where the `repo-name` template looks like
```yaml
version: 2
extends: default
repo_specific_setting:
  enabled: true
```

which we would like.

PullApprove currently says that templates can't extend from templates - would it be possible for this to happen in the future?

**Comment by davegaeddert** [comment]
Hey @jonahwh, thanks for putting this in here. It's definitely possible. Originally we were trying to keep things relatively simple so that it wouldn't be so difficult to track down what the current settings were (through a bunch of layers of abstraction). But we now have some more things like this built into the current UI which would show the end results, so maybe that's no such a big issue anymore:
![image](https://cloud.githubusercontent.com/assets/649496/21195677/60cc99a8-c1fa-11e6-9c52-b0b221a6d8dc.png)

**Comment by davegaeddert** [comment]
Going to close this for now. We decided not to do this again in v3, though it would still be feasible. Happy to hear any arguments for it, but for now it just feels like it opens things up to being unnecessarily complicated.
