### ISSUE TITLE
Github requested permissions are too broad (write access to repo)

### ISSUE THREAD

**Issue by alexeagle** [pullapprove/support#104]
We'd like to use pullapprove on the Angular project.

However, as a Google project we're bound to carefully restrict write access to our repository. Right now pullapprove requests read/write access to the repository, which allows you to make changes to Angular source code.

Can you tighten up the permissions you require from github oauth?

/cc @naomiblack @igorminar

**Comment by davegaeddert** [comment]
Hi @alexeagle, glad to hear you're interested in using pullapprove. I agree the permissions scope is too broad, but unfortunately within the current GitHub OAuth system we can't trim it down any more.

We don't ever use the write-access, but we have to have the `public_repo` scope to access endpoints for things like the lists of collaborators and teams on the repo (so that you can match reviewers to teams in .pullapprove.yml, which it looks like you're using).
https://developer.github.com/v3/oauth/#scopes

I can't provide an exact timeframe, but we expect almost _all_ of this to change soon with the new GitHub "Integrations" (https://developer.github.com/early-access/integrations/). Essentially the flow will change to giving pullapprove access to just the one repo, with more granular permissions than the OAuth flow provides. I'll try checking in with GitHub on this...

Probably not the answer you're looking for... Thoughts? We'd love to help get it up and running for Angular!

**Comment by alexeagle** [comment]
I worked around it by creating a separate github user (angular-pullapprove-bot), add to a team with repo write access, lock all our branches to prevent this user being able to push commits, temporarily give the team admin to enable pullapprove, then revoke admin and revert the settings changes it made on the master branch.

**Comment by davegaeddert** [comment]
@alexeagle great! Sounds like a bit of a hassle, but I'm glad you took the time to figure it out on your end. We'll keep that in mind for future reference.

If you have any further questions, don't hesitate to reach out!

**Comment by davegaeddert** [comment]
The new PullApprove v3 (in "open preview") is built as a GitHub App and lots of the permissions questions should be resolved. It no longer has write access to code, and you can choose specific organizations/repos to install it on. More info here: https://www.pullapprove.com

Let me know if you have any questions.

**Comment by IgorMinar** [comment]
Awesome! thanks!
