### ISSUE TITLE
Set status to pending if there is one or more pending github reviews

### ISSUE THREAD

**Issue by IgorMinar** [pullapprove/support#117]
For certain changes, the PR author sometimes wants to request reviews from more reviewers than the minimum specified in the pullapprove configuration file.

For example, normally one review is sufficient for a particular file, but in case of a particular change, the author might want another engineer, a documentation, and a performance specialist to sign off on the change. Since the file is usually modified in a way that doesn't require the specialists to be involved, it's not practical to setup more rules or subdivide the file further - we simply want to use a honor system and not have the PR be in a mergable state until these two specialists approve.

User story: As a PR author, I'd like to be able request reviews from additional reviewers, possibly not specified in the pullapprove config file. Pullapprove should recognize that there are pending reviews and keep the pullapprove PR status in the pending state until the pullapprove conditions are met *and* all of requested reviews are green. 

If the PR author changes their mind about the reviewers list, they can remove the reviewer(s).

// @alexeagle @jasonaden

**Comment by davegaeddert** [comment]
Thanks for the detail @IgorMinar, I think that makes sense. Our plan right now is to do a fairly significant rework of pullapprove to better accommodate this kind of thing and also integrate more directly with GitHub's "reviews" (also taking advantage of requested reviews). We had several ideas for how to implement it and decided to set it aside a little while ago, but we're really hoping to dig into it here soon and push things forward. I may touch base with you once we have it more finalized so that we can check specifically how it would work for your workflow. Thanks!

**Comment by IgorMinar** [comment]
ok. please update this issue when you want us to test the feature. thanks

**Comment by davegaeddert** [comment]
The new PullApprove v3 should be equipped to handle this kind of thing. With what we've got currently, you could use a setup like this to ensure that all requested reviews get approved.

Most basic example:
```yml
version: 3
groups:
  requested_reviewers:
    reviews:
      required: -1
```

A little more detail here: https://www.pullapprove.com/docs/config/reviewers/

Curious to hear if this would do what you need today? I know you've got a pretty big config file on angular -- happy to answer any questions you have about the new version. Thanks @IgorMinar!
