### ISSUE TITLE
"Signed-off-by needed on 0 commit" error

### ISSUE THREAD

**Issue by mueller-ma** [pullapprove/support#118]
Sometimes pullapprove fails with the message `"Signed-off-by" needed on 0 commit` directly after opening a PR.

**Comment by davegaeddert** [comment]
Thanks for creating the issue. Is there any more detail you can provide? Or a link to a PR? Is it happening on PRs with really large diffs or something specific like that?

**Comment by mueller-ma** [comment]
Sorry, I cannot provide more information for now. The next time this happens, I post a link to the PR here.

**Comment by mueller-ma** [comment]
Happend to me on https://github.com/openhab/openhab-android/pull/834

**Comment by mueller-ma** [comment]
Also see

- https://github.com/openhab/openhab-android/pull/963
- https://github.com/openhab/openhab-android/pull/962
- https://github.com/openhab/openhab-android/pull/961

**Comment by davegaeddert** [comment]
Not sure what the root cause of this, but at this point we're focused on PullApprove v3 and don't plan to dig into this. This is not a part of v3 and instead we suggest using a check that is built specifically for this purpose. See https://github.com/pullapprove/support/issues/115#issuecomment-356367893
