### ISSUE TITLE
Add support for a global approver

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#123]
In our repositories, we would like to be able to define an account or team that is able to provide approvals globally without being explicitly listed in the set of reviews.

This allows us to properly handle when someone is unexpectedly unavailable to review or when we need to expedite the review in some way.

Is it possible to provide a "global approver", or to define reviewers who will never be selected by pullapprove as reviewers, but are still able to give approval?

**Comment by davegaeddert** [comment]
Good question. Are you trying to keep the "global approvers" from being explicitly listed in the `.pullapprove.yml`, or from being requested and showing up in the GitHub "reviewers" UI? If it's the latter, then what I think people usually do is use a config like this, where the "global approvers" are included _last_:
```yml
reviewers:
  teams:
  - security
  - global-approvers
reviews:
  request_order: given
  request: 1
  required: 1
```

So people from "security" are always requested first (because of `request_order: given`). But if someone from "global-approvers" wants to jump in and give an approval, that will satisfy the requirement for the group.

Does that help or are you trying to remove the need for the `- global-approvers` line in every group? Happy to look at specifics if you want to share a config here or email it to support@pullapprove.com.

**Comment by josephperrott** [comment]
I am in the process of writing our config so I don't have anything to show at this point unfortunately.

Ideally I would love to be able to provide a global approvers in one place rather than having to place it everywhere.  However, I would be happy to define an "unassignable" reviewer for each group, however if we use `request_order: random` then the method you mentioned above doesn't necessarily work as I understand it?

**Comment by davegaeddert** [comment]
That's a good point. Using `request_order: random` would shuffle _everybody_ together, so that won't really work. And `request_order: given` would basically always choose the same "security" reviewers (in my example) which may not be what you want.

Things are pretty flexible so I can think of several other ways we could handle this, but if you're good with having some kind of "global-approvers" team on each group then the easiest might be to add a `request_order: shuffle_team_members` (or `request_order: random_by_team`?) which would shuffle the individual members in the team, but keep the order of the teams the same.

Maybe just send me a link/email when you get closer to a final config? I'm confident we can figure out a good solution but it would help to see what the rest of your config looks like (I'm assuming it will be fairly complex).

Thanks for asking the question!

**Comment by josephperrott** [comment]
I think that our config isn't especially complex, just very large, and you can see my WIP [here](https://github.com/josephperrott/angular/pull/1).  

Thinking about how our needs could fit better into pullapprove's configuration in general, I think that it might be valuable to have either another group other than `reviewers` that is something like `approvers` who is able to approve, but doesn't get assigned.  That would allow for other users to have either a user or team be in `approvers`

So building on your config example, it would look like this:
```yaml
reviewers:
  users:
    - groupMember
    - groupMember2
  teams:
    - security
approvers:
  teams:
    - global-approvers
```

Alternatively, perhaps there a symbol could be added to note a user/team is unassignable
```yaml
reviewers:
  users:
    - groupMember
    - groupMember2
  teams:
    - security
    - -global-approvers
```

I want to make sure if there is anything that needs to change it could be useful beyond just our use case.

**Comment by davegaeddert** [comment]
Totally agree with making sure any changes are useful beyond angular ;)

Adding "approvers" is an interesting idea. How common do you think that reviewers vs approvers distinction is? I know I've seen it in a few places (kubernetes?) but personally I don't have a good feel for how common that is. Admittedly, that terminology has never really clicked for me (but I've never worked directly in a team that uses it).

With the way your config looks, do you think adding a new `request_order` would work for your situation? I'll give this a little more thought but so far I think that's the simplest solution that, so far as I can tell, checks all the boxes and is a much smaller change. People use `teams` way more often than `users`, so I'm not sure how concerned I am about what happens if someone wants to combine the two in this scenario (it seems pretty easy and maintainable to set up a team if you're trying to achieve this global/fallback approver behavior). Another benefit (in my mind) of going that route would be that if everyone in "security" is unavailable for some reason, review requests could then be sent to the "global-approvers" as the next available team.

Would all of the people in your global approvers also have "admin" (or "write"?) permission on the repo? I guess another thing I'm wondering now is if we could/should leverage that somehow since they would be the same people who could merge regardless of required statuses, etc. Maybe there are situations where those people are not the same though. For example, you could imagine an admin-only [command or syntax](https://docs.pullapprove.com/reviewed-for/) that let's them override the entire review process (another scenario being an admin is concerned about a PR, and wants to _pause_ the review process instead of expediting it).

**Comment by josephperrott** [comment]
Kubernetes having the same concept might come from the fact that it was originally created by Google and we this concept internally for large scale changes in which its unrealistic to ask for approval from every owner in such a large monorepo.  This is similar to what we are seeing in Angular where we have ~20 different owners across our repo, with more expected as we continue to grow our repo.

A new `request_order` could work, though I am not 100% sure I understand how you it would work based on your description.

For our exact case all of our global approvers currently have admin, but that isn't necessarily intended to always be the case.  If we were to be looking to have this special syntax that referenced, I think it would make the most sense to have a config that lists users who are allowed to use this syntax rather than relying on special repo permissions.  As it currently stands any user can look at the `.pullapprove.yml` file and understand/interpret all of the review configuration.  If permissions on the repo come into play then we are now managing review configurations in two places.  Personally I like the idea of keeping all of the concerns in one place in the yaml file.

**Comment by davegaeddert** [comment]
What I was suggesting with `request_order: shuffle_team_members` is that the order of the teams themselves stay the same, but the members of the team are shuffled before selecting reviewers. (Maybe there is a better term for this?) This way you can put the "global-approvers" last in the teams order and realistically nobody from that team will ever get formally _requested_ for review. But, an approval from someone in "global-approvers" would still be valid if they want to jump in and expedite the process. 

So in the original example:
```yml
reviewers:
  teams:
  - security
  - global-approvers
reviews:
  request_order: shuffle_team_members
  request: 1
  required: 1
```

Since `request: 1`, it will shuffle the team members, and then pick the first reviewer from "security". This would be different from `request_order: random` because that would mix "security" and "global-approvers" together, and then pick someone.

At least in my understanding that would answer your original question, since "global-approvers" would never be selected as reviewers but could still give approval.
> Is it possible to provide a "global approver", or to define reviewers who will never be selected by pullapprove as reviewers, but are still able to give approval?

Does that make more sense?

**Comment by josephperrott** [comment]
That definitely clears up what you were meaning in your previous comments.

How would this work in a mixed teams/users situation?  For instance:
```yaml
reviewers:
  users:
    - groupMember
    - groupMember2
  teams:
    - security
    - global-approvers
reviews:
  request_order: shuffle_team_members
  request: 1
  required: 1
```

Would this just assign a "random"/"shuffle" from members of security?  Or does it randomize the union of the `users` and `security` group?  


In talking with our leads, we are looking to hopefully move away from using exclusively teams.  We will likely end up with this mixed `teams` and `users` situation.

I definitely can see how this new `request_order` could be useful for our use case, though I am unsure if there is other usage of this `request_order`

**Comment by davegaeddert** [comment]
Yeah the behavior with mixed teams/users isn't obvious, which is why I mentioned earlier that people pretty much exclusively use teams with pullapprove (and usually one team per group) so I wasn't too worried about it. Sorry if what I said before wasn't clear! We may end up adding a `request_order` like this later anyway, but if you're serious about moving to `users` then maybe it isn't the right solution for your use case.

One other question... do you anticipate there being multiple sets of people who can act as global approvers?
```
    reviewers:
      teams:
        - fw-docs-intro
        - framework-global-approvers-for-docs-only-changes
        - framework-global-approvers
```

I would have to think through some other pros/cons of this, but maybe the clearest solution is to have a top-level `admins` in pullapprove. If an admin approved a PR, it would override any of the groups and set the status to approved. Likewise if they rejected. There are other ways we could achieve this through conditions etc. but it becomes pretty convoluted for what I think would be a pretty common use case (I've helped other customers work through "stuck" PR questions in the past). Something roughly like:

```yml
version: 3
admins:
  users: [admin1, admin2]
groups:
   ...
```

**Comment by josephperrott** [comment]
We could stick with groups if we have to, but using the groups leads to the indirection of storing the config of our reviews in multiple places (the `.pullapprove.yml` file and the github team settings).

In asking @IgorMinar about his expectations for multiple sets of people who can act as global reviewers we worked through better defining some of our use cases we are worried about:

- **TLs performing reviews to speed up processes.**
  This ends up covering things like unexpected OOO for reviews, emergency fixes, etc.
- **Large Refactorings**
  When a change happens across a large number of files, often there ends up being far too many reviewers to be able to reasonably get the review done in a quick fashion.
- **Comments/Docs changes in code**
  Since our code is documented in some comments, we have our docs team review changes that are in our code, but only update comments.
 
A true global approver covers the first two use cases, but doesn't quite work for the third.

So I guess we would like to have one group that is global approvers (use case 1 and 2) and also allow for unrequested reviews from another group.

In talking with Igor, I realized that I think that I am approaching this from a slightly different angle than you are.  Pullapprove is primarily defining rules for who should be requested as a reviewer for a PR and I am looking to primary define who is allowed to approve a PR.

**Comment by davegaeddert** [comment]
This is helpful, thanks. I think what I will do first is look into the possibility of a "symbol"/prefix like you suggested for marking specific users/teams unrequestable within a group. It sounds like that could help in all three scenarios. Separately I'll consider what it would look like to add an "admin" tier as a true "these people can immediately approve/reject any PR at any time" solution -- that's a more involved change so I just want to make sure I'm not missing anything. I think both of those ideas have value beyond angular.

Yeah in pullapprove "reviewers" are basically the same as "approvers", at least as far as I understand it. I get the feeling though that you could separate those responsibilities if you wanted to though, via groups. [Implementation details](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/approve/approvers) make a big difference here and I could very well be misunderstanding the specifics, but could you take a stab at separating those responsibilities with structures like this? Seems like they're both responsible for actually doing review, those reviews are just staged and have different importance?
```yml
groups:
  compiler-reviewers:
    reviewers: ...
    reviews:
      required: 1
      request: 2
  compiler-approvers:
    conditions: ["'compiler-reviewers' in groups.approved"]
    reviewers: ...
    reviews:
      required: 1
      request: 1
```

Anyway, I'll look at implementing the symbol/prefix idea first and we can go from there. Let me know if you have other questions or suggestions! Thanks for working through this.

**Comment by josephperrott** [comment]
We plan on having stages like this as well, however the "global approvers" are not a second stage of review, but instead are just reviewers who will never be requested for review.


I think the symbol/prefix should allow for us to perform this task.

**Comment by davegaeddert** [comment]
Yeah sorry to muddy the waters there. I think we're clear on the "global approvers" use. That last example I threw in was just my understanding of the kubernetes flow to show how you could distinguish "reviewers" from "approvers" in pullapprove, even though it doesn't have that distinction built-in.

I got the symbol/prefix added and it's ready for you to try. I will document it once you've had a chance to try it out, but the symbol I went with was `~`. So:
```yaml
reviewers:
  users:
    - groupMember
    - ~groupMember2
  teams:
    - security
    - ~global-approvers
```
That will prevent it from including those users/teams when sending the actual review requests (technically it will throw them in the "unavailable" bucket), but their reviews will still be valid for the group.

Let me know what you think. Thanks!

**Comment by davegaeddert** [comment]
I'm going to close this for the time being since we've added a few features to help make these scenarios possible. Most notably, the "optional" group type: https://docs.pullapprove.com/config/type/

https://docs.pullapprove.com/examples/global-reviewers/
