### ISSUE TITLE
PullApprove re-requesting reviews unnecessarily when reviewed_for: require is present

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#138]
We have begun to include `reviewed_for: require` for some of our groups ([example](https://github.com/angular/angular/blob/e0dfa42d6e656124f3c3d78e178b1bf091b38e79/.pullapprove.yml#L683)) which requests reviews.

It seems that if one of the requested reviewers performs a review without including `Reviewed-For: <group>` in the review comment, PullApprove re-requests reviews. This triggers emails to the reviewer that their review has been requested again. This is particularly confusing when the reviewer has requested changes, but the PR immediately removes the requested changes status and instead shows as regular pending.

An example of this situation can be seen [here](https://github.com/angular/angular/pull/35464#pullrequestreview-432442608).

- `pkozlowski-opensource` provides a review without marking `Reviewed-For`, implicitly reviewing `fw-core` and `required-minimum-review`.
- Immediately after PullApprove re-requests `pkozlowski-opensource`'s review on the PR, changing the "Requested Changes" state on Github.
- `pkozlowski-opensource` provides a review for `fw-core` (which does not have the requirement of `Reviewed-For:` requesting changes.
- Immediately after PullApprove re-requests `pkozlowski-opensource`'s review on the PR, changing the "Requested Changes" state on Github.

The [PullApprove status page](https://app.pullapprove.com/report/?url=https%3A//storage.googleapis.com/pullapprove-storage/reports/8a840c98-f820-4cc5-8a57-b70a546c4504.json%3FExpires%3D1597586745%26GoogleAccessId%3Dpullapprove-reporter%2540pullapprove.iam.gserviceaccount.com%26Signature%3DgExoOUpW2ya6F2qj2nl3Im2J94F90TzNmJyj%252FilTbUBDNR9h0otPAfLhc9GjuLGzXJhuhoVdIhMjt9BvTqqJLE2cEu2oBMXebnNkmJNrMWfDWjEigzeBQcPsb7VEggklGNPtBKeGisjorOO3z2998ha%252BQ67hOcLV7uh8I4RHkA3Rse%252BVMb34ZCPANN28GxB4%252F7nuYuhZJJ9VYpTidboQVB401HpIo8wZDu738DLWkPJcLfU65QeBxvSpER4QiwczgC95YeqIXv229wCpnFI1OwNnmqxqeIU0FiN3feCQm8R5mz5ArPTddcIt%252FpOp7beSKeCpwF5H%252F6XkqKpO%252FYrknA%253D%253D&fingerprint=cbd3d5597de3d3d8b0d07ec038d0e65f) correctly notes that `pkozlowski-opensource` is in a "rejected" state for `fw-core` and `required-minimum-review`.

It seems that PullApprove should not be re-requesting a review in this case as the "Requested Changes" has simply placed the expectation of the next action on the PR author.  Placing a pending status places the expectation back on `pkozlowski-opensource`.

My expectation would be that PullApprove would only re-request the review when someone triggers a terminal state in the review process (currently that would only mean "Approved"), but has not `Reviewed-For` all of the groups for which they are requested, either via explicity or implicit `Reviewed-For`.

cc: @pkozlowski-opensource

**Comment by davegaeddert** [comment]
So in this case it looks like @pkozlowski-opensource was re-requested because of the public-api group `request: -1` and because his "request changes"/rejection didn't apply to public-api (because `reviewed_for: required`). So as far as public-api is concerned, he hasn't reviewed for that yet and it is going to make sure everyone is requested to do so (`request: -1`).

![image](https://user-images.githubusercontent.com/649496/84922873-16a45580-b08c-11ea-98fb-ad2c359a58c9.png)

Confirmed in the debug tab of the status you sent:
![image](https://user-images.githubusercontent.com/649496/84922949-3176ca00-b08c-11ea-8564-dad48dd1d7f6.png)

Thoughts?

**Comment by josephperrott** [comment]
I suppose that makes sense when viewed from the pullapprove system/pullapprove config maintainer.  But from a reviewer perspective, I think that anyone in `users_pending` would be thought to already be requested.

I think PullApprove is just being overzealous by requesting again when the review process is still in a pending state in terms of review workflows.  When someone requests changes, they are wanting a change to happen and then look again, the review is still ongoing so it doesn't need to be asked for again.

This is a different case than when a user approves without noting `Reviewed-For:`, in this case it makes sense for PullApprove to re-request because the reviewer attempted to end the review process, but more review scopings are needed.

**Comment by davegaeddert** [comment]
Isn't this an example of the "user approves without noting Reviewed-For" case? His "request changes" never applied to the public-api group, because he never specified it. So I think it is re-requesting for more review scopings, like you're suggesting.

I see him leaving two reviews. [This generic one](https://github.com/angular/angular/pull/35464#pullrequestreview-432427887), which will apply to all the groups that don't require Reviewed-for, and [this one for fw-core specifically](https://github.com/angular/angular/pull/35464#pullrequestreview-432442608). If he would have left a review with "Reviewed-for: public-api" (or added that to his fw-core review), then it would not have requested him again and would have worked like you're saying here:
> When someone requests changes, they are wanting a change to happen and then look again, the review is still ongoing so it doesn't need to be asked for again.

**Comment by josephperrott** [comment]
I can see how it is two reviews, however if there is two reviews occurring, its odd to overwrite the state of one of the reviews (when it becomes request change), with another (pending).

I think it works out in a reviewers mind more often that a rejection/failure in a review is general to all areas the reviewer is responsible for during the temporary time while the comments are addressed.  Whereas, approval of a specific area makes more sense as you want to make sure that it's explicit.  From my perspective, specificity in the failure/rejection case is less important than it is in the approval case.


You can see the confusion occur [here](https://github.com/angular/angular/pull/37678#pullrequestreview-437846756) as well, where the reviewer ends up fighting with PullApprove just to get it to remain in a changes requested state, when the reality is that the requested changes are general anyway and have little to do with any of the groups they are responsible for reviewing for.

**Comment by davegaeddert** [comment]
This is helpful, thanks for the explanation.

So is the Reviewed-for behavior on rejections the biggest root question here? What if we added another option like `reviewed_for: required_for_approval` (not sure about the name...)? Then you could just use that instead of `reviewed_for: required` and things would flow like you're saying?
