### ISSUE TITLE
Support for PullApprove to express why specific users reviews are requested

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#139]
When a user approves a PR, but is missing a `Reviewed-For` required group, PullApprove re-requests the user.  From the user perspective, it looks like they approved fully and then were asked to review entirely again.

Is it possible to build support for PullApprove adding a comment when reviews are requested expressing what groups are being requested from users?

I suppose, the request would be for a stripped down version of what is shown in the `Groups` tab on the PullApprove status page in a comment. Much of the metadata would not be necessary to include, but including information about reviewers for each group and their review state would allow for reviewers to understand what is being asked of them.

While the information is available in the PullApprove status page, having it colocated where reviewers are already performing there tasks would make it more discoverable.  Currently, opening the PullApprove status page via the status link on the PR is not immediately apparent to many and additionally is an intimidating prospect for those who don't understand the review assignment system.

**Comment by davegaeddert** [comment]
Totally hear you on the idea of more visibility/clarity. I think this is probably the biggest problem area we have at this point.

We do actually have a notification event that you can use today, which might help. A little buried, but `pullapprove.group.requested_reviewers` at the bottom of the notification docs (https://docs.pullapprove.com/config/notifications/). Note that this triggered per-group though, so depending on workflows, you may get back-to-back comments.

Example:

```yml
notifications:
- when: pullapprove.group.requested_reviewers
  comment: |
    {{ event.group }} review requested from {{ text_list(event.requested_reviewers.mentions, "and") }}
```

![image](https://user-images.githubusercontent.com/649496/84933260-4018ad80-b09b-11ea-8c66-cda2f2b9ea75.png)

Does this help for the time being? On a related note... if we could output the status info in the "Checks" tab (can't believe this API is still in "preview"...), do you think that would be colocated enough, or still a step too far removed?

We're pretty heavily dependent on GitHub's data model right now. Seems like it would be really nice (for PullApprove and otherwise) if an explanation/description could be attached to a review request. They kind of do this in their code owner assignment emails, but I don't believe there are any exposed APIs for this:
![image](https://user-images.githubusercontent.com/649496/84933875-24fa6d80-b09c-11ea-9e55-5b56865f683b.png)
