### ISSUE TITLE
Reset approval status after closing and re-opening PR

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#14]
This would be a setting for .pullapprove.yml. Maybe `reset_on_closed` or `reset_on_reopened`?

@vaidik thanks for this one!

**Comment by vaidik** [comment]
`reset_on_reopened` sounds reasonable. But how I look at this is a problem of resetting on change of code first and then the state of pull request. Consider this:
1. Open a pull request with 5 commits and lets say with diff d1.
2. Got it approved.
3. Pushed more commits. But these commits may have changed the diff or may not have changed the diff. In case of the diff getting changed, d1 changes to d2. A new code review is required and hence approval status should be reset. In case of diff not getting changed i.e. d1 remaining d1 because, lets say, someone just squashed the commit - we don't need another round of review because nothing really changed.

If this is taken care of, then from project to project, the requirement of reseting approval status in case of pull request being closed and opened again may vary. If the code has changed i.e. new commits with new code was pushed then the approval status should get reset anyway according to the logic I described above. But in the other case where the code does not change, some people may want another round of approval. For that, I think `reset_on_reopened` sounds reasonable. But what should be the default behavior? Well, I don't know. Perhaps another round of approval should not be required because people may accidentally close pull requests and may want to reopen and merge. But it should be configurable definitely.

**Comment by davegaeddert** [comment]
Yeah, I hear you on the diff changes. I've actually had issue #2 sitting there for a while, just waiting for the day it was relevant. It seems like it applies to the `reset_on_push` setting as much as anything -- since the push is when the diff may or may not have changed.

I like the idea of having `reset_on_reopened` as an available option. One scenario for our team in particular is sometimes a PR will get closed and put on hold for a while, but we leave the branch knowing that it may come back in a few weeks. A few weeks later, that code hasn't actually changed but the PR is re-opened and before somebody merges it in we like to look it over one more time and make sure there aren't any un-testable conflicts that would have come up since.

**Comment by davegaeddert** [comment]
I added `reset_on_reopened`, basic initial docs can be found here: http://docs.pullapprove.com/yaml/reset_on_reopened/
