### ISSUE TITLE
Feature Request: Add labels regardless of PR status

### ISSUE THREAD

**Issue by jessicajaniuk** [pullapprove/support#143]
We attempted to use the labels feature on the angular team, and we found some odd behavior. We have a process in which we apply labels for specific components within the angular framework that match up to code paths. So for example, based on a code path, we apply "comp: core" or "comp: compiler", etc. We thought maybe pullapprove could solve this for us automatically. We added the following config within our groups thinking that with this, regardless of any state the PR would be in, the proper label would be present:

.pullapprove.yml
```
    ...
    conditions:
      ...
    labels:
      pending: "comp: compiler"
      approved: "comp: compiler"
      rejected: "comp: compiler"
    reviewers:
      ...
```

What we're seeing is this label getting added and then getting removed almost immediately, and we're not sure why that's happening. Maybe it's getting confused when there's multiple commits or if the PR is in multiple states? Definitely not what we expected. We're rolling this config change back, unfortunately.

It would be great if we could have a PullApprove option to just apply a label to a PR regardless of state. A simple label list would be wonderful.

**Comment by jessicajaniuk** [comment]
You can also see an example of this label removal activity in this PR, which is the revert PR. 
https://github.com/angular/angular/pull/40053

**Comment by davegaeddert** [comment]
Thanks for the detail @jessicajaniuk! That's not _exactly_ what we had in mind with the labels feature, but I see how you got there and how using it this way could make sense (or something like it).

I took a look and I think this is just a simple order of operations difference -- I went ahead and swapped it so that if the same label is used on multiple groups/states, it will be _added_ instead of being removed. (Originally labels were assumed to be unique across groups/states.) You're welcome to try it again if you're still up for it!

I do agree that using it this way looks a little awkward with the config settings we have currently. I'll keep that in mind as things continue to evolve. If you have a specific suggestion for what that YAML could look like (knowing how angular uses pullapprove), I would be happy to hear it.

**Comment by jessicajaniuk** [comment]
@davegaeddert We'll give it a try and let you know how it goes. Thanks for your prompt reply! The team always appreciates it.

**Comment by jessicajaniuk** [comment]
@davegaeddert We rolled forward our change today, and it's working great so far. Thanks for your fix! In regards to suggestions for the YAML syntax, there's a simple approach that I think would work well and would be backwards compatible. 

```
    ...
    conditions:
      ...
    labels:
      default:
        - "comp: core"
        - "comp: compiler"
        ...
      pending: "pending"
      approved: "merge"
      rejected: "blocked"
    reviewers:
      ...
```

The `default` option wouldn't be affected by PR status. Whatever list of labels are there would just be applied.

Thanks again for your quick fix!
