### ISSUE TITLE
Ignore merge commits for reset_on_push=true

### ISSUE THREAD

**Issue by gabrieljoelc** [pullapprove/support#37]
Because we use GitHub Flow, we don't set `reset_on_push` to `true` because we don't want to have to re-review for merges from `master` into the feature branch. It'd be nice if we maybe had a different flag that ignores merges from `master` so we could do something like:

```
reset_on_push: true
ignore_merge_commits: true
```

**Comment by crazydog115** [comment]
:+1:

**Comment by bremart1** [comment]
I would ignore only clean merges. (No conflicts).

**Comment by JPLemelin** [comment]
@davegaeddert  What is the state of this issue ?
We are considering to roll back to GitHub PR review system with the new system of code owners (https://github.com/blog/2392-introducing-code-owners)

**Comment by davegaeddert** [comment]
@JPLemelin no update, unfortunately. We started working on this a while back but got hung up somewhere...can't remember what it was exactly. Do you know if the GitHub review option here does this the way you want it to?
![image](https://user-images.githubusercontent.com/649496/31400405-171dc28a-adb5-11e7-9c17-1da7d5193275.png)

In the end, we admittedly did slow down on adding features and stuff once the GitHub review system was added since we didn't want to spend a bunch of time trying to build things that they also do. That being said, we do have plans for a new version of PullApprove that would be built-in of the new GitHub App system. It would function more as an extension/automation of the built-in PR reviews instead of being two separate things. Unfortunately, we just haven't had time to play that out yet, but we really want to!

Sorry I know that's not a very helpful response. I'd say that if the new GitHub review system works for you as-is, then definitely use it. If there are things that it just doesn't do and you really need, we'd love to hear what they are because those are the things we need to focus on!

**Comment by stivni** [comment]
I haven't tested it yet, but according to https://help.github.com/articles/enabling-required-reviews-for-pull-requests/ it should only require new approvals if the commit was *code-modifying*

> Optionally, select Dismiss stale pull request approvals when new commits are pushed. This dismisses a pull request approval review when a code-modifying commit is pushed to the branch.

I'll try to verify that assumption when I find more time to poc it.

**Comment by JPLemelin** [comment]
GitHub with the option of `Dismiss stale pull request approvals when new commits are pushed.` It will not require a new approvals when we do an `Update Branch` without conflict, otherwise as far as i know it will be considring as _code-midifing_. 

PullApprove with the option `reset_on_push`, an `Update Branch` without conflict will require a new approvals.

**Comment by davegaeddert** [comment]
The new PullApprove v3 is completely built around GitHub reviews -- so the settings that GitHub has for dismissing reviews are the thing to use. More info about the new version here: https://www.pullapprove.com
