### ISSUE TITLE
Webhook not created on repo

### ISSUE THREAD

**Issue by eminetto** [pullapprove/support#6]
Can i use a webhook on Github to sync my pull requests?

**Comment by davegaeddert** [comment]
@eminetto I'm not quite sure I follow. What are you trying to do? If you add a repo to PullApprove, it will set up its own webhooks (did they not get added?). It does not go back and retroactively sync PRs to the PullApprove site, since they serve no purpose, but if there are PRs that were open when you added the repo to PullApprove, you can click the "sync open PRs" button to add them to PullApprove. Does that help?

**Comment by eminetto** [comment]
The webhooks wasn't created. Maybe because i have only push access to the repository? 
Can i do this manually?

**Comment by davegaeddert** [comment]
@eminetto you're right, it's because you have push access but not admin access. You can now **only** add repos that you have admin access to...

**Comment by davegaeddert** [comment]
@eminetto just FYI, I made some more changes around permissions, to better reflect the permissions that already exist in GitHub -- for an organization repo, only **organization owners** can modify billing info, start plans, etc.
