### ISSUE TITLE
Bot comments

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#81]
A PullApprove bot that comments on PR's has been a work in progress for a little while now. A few things need to be finalized:
- when exactly it comments, is that configurable
- when the bot does or intentionally does not mention users

Use cases:
- notifying reviewers via GitHub notifications that it is time for them to review a PR
- notifying authors of failed checks (`signed_off_by` #65)

**Comment by cdeszaq** [comment]
In addition to adding comments, triggering other things based on comments would be good too. (eg. rebases, merges, etc.) In those cases, status of those operations via comments makes a lot of sense.

Another thing to think about would be if the bot should clear out some of it's previous statuses so that it doesn't overly clutter the comments.

**Comment by davegaeddert** [comment]
@cdeszaq agreed on the avoiding comment clutter aspect. At least for some of the behaviors, the thinking would be that pullapprove could make one comment, and then make updates to that comment as opposed to making new comments (similar to how Codecov does PR comments by default). There are pros/cons here so we're evaluating different options.

It's possible, but I'm not sure that pullapprove will get into triggering rebases, merges, etc. We'll give that some thought though too.

**Comment by davegaeddert** [comment]
PullApprove v3 has comment notifications built-in now, with triggering based on different events and access to the data for those events. More info can be found here: https://www.pullapprove.com/docs/config/notifications/
