### ISSUE TITLE
Automatic merge after enough approvals

### ISSUE THREAD

**Issue by googol** [pullapprove/support#9]
It would be excellent if pullapprove could trigger a merge once all the pull request statuses are 'success'.

**Comment by davegaeddert** [comment]
Thanks @googol -- I'll keep this in mind as we think about next steps! Let me know if you have any other ideas.

**Comment by thomaspaulmann** [comment]
It would be great to decide between an automatic merge or rebase. Rebase generates a much cleaner history and does not distort the contributor stats.

**Comment by jaymecd** [comment]
It may depend on repo setting, since couple months ago Github made possible to choose: merge or squash. Personally I prefer squashed one, as history remains plain.

**Comment by cdeszaq** [comment]
There are times where you want to keep more than 1 commit (ie. logical commits), but also want to squash away any "addressing review comments" commits, so GitHub's SquashMerge capability isn't great (it also messes with the commit messages...).

Being able to trigger a "rebase onto target branch" or "merge to target branch" via a comment on the PR would be great.

In the ideal world, the "common" workflow would be fantastic to automate:
1. Trigger (via comment) a rebase if-possible (retaining approval status, or reverting it if the diff changed
2. Trigger (via comment) a full squash (if possible), ideally taking a "new" comment if given, or using the bottom one otherwise
3. Trigger (via comment) a merge if-possible (ideally a FF merge...)

**Comment by davegaeddert** [comment]
At this point we're thinking that PullApprove ([new v3 update here](https://www.pullapprove.com)) should not be responsible for this. Instead, this should probably be a specific GitHub App that handles all the nuances of automatically merging (whether or not you use PullApprove).

We've actually been using such a thing ourselves which you can find here: https://github.com/dropseed/automerge

It is purely built to run the way we want it to, and free to use for the time being, but PRs are welcome if anybody wants to push it further.
